# Generated by Django 3.0.6 on 2020-05-22 02:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enduser', models.CharField(max_length=255, verbose_name='E/U')),
                ('hansha', models.CharField(max_length=255, verbose_name='販社')),
                ('product', models.CharField(max_length=255, verbose_name='プロダクト')),
                ('sbkk', models.CharField(blank=True, max_length=255, verbose_name='SBKKトスアップ')),
                ('hansui', models.CharField(blank=True, max_length=255, verbose_name='販推')),
                ('sisuisin', models.CharField(max_length=255, verbose_name='SI推進')),
                ('hitouch', models.CharField(blank=True, max_length=255, verbose_name='ハイタッチ担当')),
                ('donyusien', models.CharField(blank=True, max_length=255, verbose_name='導入支援')),
                ('jutyu', models.DateField(verbose_name='受注時期')),
                ('donyu', models.DateField(verbose_name='導入時期')),
                ('kakudo', models.CharField(blank=True, max_length=255, verbose_name='確度')),
                ('kyougou', models.CharField(blank=True, max_length=255, verbose_name='競合')),
                ('kousinjikoku', models.DateField(auto_now=True, null=True, verbose_name='')),
                ('archiveflag', models.BooleanField(default=False, verbose_name='')),
                ('mitumorigaku', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='見積もり金額')),
                ('arari', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='粗利額')),
                ('joukyo', models.CharField(blank=True, max_length=255, verbose_name='状況')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanryoflg', models.BooleanField(default=False, verbose_name='')),
                ('task', models.TextField(blank=True, verbose_name='タスク')),
                ('kigen', models.DateField(blank=True, verbose_name='期限')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='cms.Anken', verbose_name='案件')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanryoflg', models.BooleanField(default=False, verbose_name='')),
                ('task', models.TextField(blank=True, verbose_name='タスク')),
                ('kigen', models.DateField(blank=True, verbose_name='期限')),
                ('tantou', models.CharField(blank=True, max_length=255, verbose_name='担当')),
                ('anken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cms.Anken', verbose_name='案件')),
            ],
        ),
        migrations.CreateModel(
            name='Sintyoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinyubi', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='記入日')),
                ('shosai', models.TextField(blank=True, verbose_name='進捗内容')),
                ('sintyoku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintyokus', to='cms.Anken', verbose_name='案件')),
            ],
        ),
    ]
